name: continous-integration-marco-ramirez

on:
  push:
    branches:
    - master
    - 'feature*'
    - 'hotfix*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    steps:
        - name: Pruebas de SAST
          run: echo "Ejecución de pruebas de SAST"
        - name: Create new credentials file
          uses: nowactions/envsubst@v1
          with:
            input: ./credentials.ini.tpl
            output: ./credentials.ini   
          run: |
            export USERNAME=${USERNAME}
            export PASSWORD=${PASSWORD}
            envsubst < credentials.ini.tpl > /tmp/credentials.ini
        - name: Build docker image
          run: |
            docker build -t devops_ws . --tag devops_ws_$(date +%s)