name: continous-integration-marco-ramirez

on:
  push:
    branches:
    - master
    - 'feature*'
    - 'hotfix*'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
        - name: Checkout master
          uses: actions/checkout@master
        - name: Pruebas de SAST
          run: echo "Ejecución de pruebas de SAST"
        - name: List
          run: |
            ls -l
            pwd
        - name: Create new credentials file
          uses: nowactions/envsubst@v1
          with:
            input: ./credentials.ini.tpl
            output: ./credentials.ini
        - name: Crear el archivo de credenciales
          env:
            ${USERNAME}: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
          run: |
            echo 'Username: ${{ secrets.USERNAME }}'
            echo 'Pass ${{ secrets.PASSWORD }}' | sed 's/./& /g'
            echo 'Username var: USERNAME'
            echo 'Pass var: PASSWORD'
            export USERNAME=${USERNAME}
            export PASSWORD=${PASSWORD}
            sudo envsubst < credentials.ini.tpl > /tmp/credentials.ini
            ls -l
            pwd
            cat /tmp/credentials.ini


