name: continous-integration-marco-ramirez

on:
  push:
    branches:
    - master
    - 'feature*'
    - 'hotfix*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    steps:
        - name: Verificar branch master
          uses: actions/checkout@master
        - name: Pruebas de SAST
          run: echo "Ejecución de pruebas de SAST"
        - name: List
          run: |
            ls -l
            pwd
        - name: Create new credentials file
          uses: nowactions/envsubst@v1
          with:
            input: ./credentials.ini.tpl
            output: ./credentials.ini
        - name: Crear el archivo de credenciales
          run: |
            echo $USERNAME
            echo $PASSWORD
            export USERNAME=${USERNAME}
            export PASSWORD=${PASSWORD}
            sudo envsubst < credentials.ini.tpl > ./credentials.ini


