name: pull-request test

on: [pull_request]

jobs:    
    check_file_existence:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            
            - name: Pruebas de SAST
              run: echo "Ejecución de pruebas de SAST"                  
            
            - name: Check if file exists
              run: |
                if [ -f ./allow_pull_request.txt ]; then
                  echo "File exists."
                  echo "Permitiendo pull request"  
                  exit 0
                else
                  echo "File does not exist."
                  echo "Impidiendo pull request"
                  exit 1
                fi
            
            